In [18]:
from torch.distributions.kl import kl_divergence
import torch

from torch.distributions.kl import register_kl

In [41]:
import torch.nn.functional as F

P = torch.Tensor([0.36, 0.48, 0.16])
Q = torch.Tensor([0.333, 0.333, 0.333])
out = F.kl_div(Q.log(),P, reduction = "sum")
out


tensor(0.0863)

In [54]:
a = torch.Tensor([0.1,0.1,0.1])
b = torch.Tensor([0.2,0.2,0.2])
c = torch.Tensor([0.3,0.3,0.3])
d = torch.stack([a,b,c])

In [55]:
-torch.sum(d,
           dim=-1,
           keepdim=True)

tensor([[-0.3000],
        [-0.6000],
        [-0.9000]])

In [43]:
mean = torch.mean(P)
var = torch.var(Q)



tensor(0.)

In [20]:
@register_kl(Normal, Normal)
def kl_normal_normal(p, q):
    kl_divergence(p,q)

NameError: name 'Normal' is not defined

In [21]:
mu = torch.Tensor([0] * 100)
sd = torch.Tensor([1] * 100)

p = torch.distributions.Normal(mu,sd)
q = torch.distributions.Normal(mu,sd)

out = torch.distributions.kl_divergence(p, q).mean()
out.tolist() == 0

True

In [25]:
torch.distributions.kl_divergence(p, q)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [35]:
a = torch.randn(1, 3)
a

tensor([[-0.7883, -0.3505,  1.0756]])

In [37]:
torch.sum(a, keepdim = True)

TypeError: sum() received an invalid combination of arguments - got (Tensor, keepdim=bool), but expected one of:
 * (Tensor input, *, torch.dtype dtype)
 * (Tensor input, tuple of ints dim, bool keepdim, *, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of names dim, bool keepdim, *, torch.dtype dtype, Tensor out)


In [39]:
torch.clamp(0,1,-1)

TypeError: clamp() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (Tensor input, Number min, Number max, *, Tensor out)
 * (Tensor input, Tensor min, Tensor max, *, Tensor out)
